### PR TITLE
Changing the Discovery client type to interface

### PR DESCRIPTION
**Pull request by nandajavarma**

### CODE REVIEW

**Comment by angelbarrera92** [comment]
How does this change affect "clients"/"users"? (other go components)

**Comment by nandajavarma** [comment]
> How does this change affect "clients"/"users"? (other go components)

It doesn't at all. [This PR](https://github.com/sighupio/fip-results-controller/pull/7/files) used the client replaced with `DiscoveryInterface`. Works exactly the same.

**Review by angelbarrera92 — APPROVED** [review]
LGTM!

**Comment by angelbarrera92** [comment]
Can we push this PR to master @nandajavarma?

**Pull request merged**
